Rework error handling for OpenStack related collectd plugins
When the OpenStack services cannot be polled due to authentication
issues (eg invalid username/passwod), collectd logged this message:
AttributeError: 'NoneType' object has no attribute 'status_code'

This change raises a KeystoneException when the plugin can't
authenticate against Keystone.
All other exceptions are logged as well.

Change-Id: I97c527d30b519989e43c1cfc0db4ce9d1dc50ca8