ruby1.9.1-dev in a test requirement
Without this package installed on the system the following error triggers when bundle attempts to install the "json" package with native extensions:

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:1:in `<main>'

Gem files will remain installed in /home/elemoine/src/fuel-plugin-lma-collector/.bundled_gems/ruby/1.9.1/gems/json-1.8.3 for inspection.
Results logged to /home/elemoine/src/fuel-plugin-lma-collector/.bundled_gems/ruby/1.9.1/gems/json-1.8.3/ext/json/ext/generator/gem_make.out
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
ERROR: InvocationError: '/usr/local/bin/bundle install --path /home/elemoine/src/fuel-plugin-lma-collector/.bundled_gems'

Change-Id: I07d1b69a10892238aea7f21ecb8d7044f39b8ab1