Fix Pacemaker collectd plugin
Error may happen:
  AttributeError: 'NoneType' object has no attribute 'iter'

Change-Id: I58ead0b0a6e9c84df853b7c9c343b661723e99d8
(cherry picked from commit 37459d65c97ec6cf4adc4a835c495410561b2c98)